### ISSUE TITLE
Rename this project?

### ISSUE THREAD

**Issue by jbilcke** [jbilcke/latent-browser#3]
web4 is a good name to describe this whole new era of **apps created on demand by AIs** (as opposed to centralized and decentralized apps that are created "in advance" of the demand), as this is still the web (it uses internet services, and web rendering techniques for text, images, sound, videos..)

but the name is not so good for a github repo, as they are similar named projects

some serious candidates:

- `vanadium` (Chrome has the atomic number 24, and Vanadium is 23)
- `latent.search` (.search domains are not available yet
- `latent-browser`

**Comment by gragland** [comment]
I kind of like latentbrowser.com (available). I also happen to own lostinlatentspace.com, which I'm happy to donate, but maybe a bit too long and doesn't sound like a browser. when i hear web4 my first thought is crypto.

**Comment by jbilcke** [comment]
ha, I see what you mean by crypto..!

 there are more than 2000 repos called web4 out there, and it sounds like a common theme:

https://github.com/search?q=web4

well, I will give it a thought! I think we are lucky that "latent" isn't a word too much popular (yet) among domain squatters
